// This file was auto-generated by "convex dev".
// There is one server.d.ts file per function directory.

import { FunctionDefinition } from "convex/server";

interface DataModel {
  users: {
    _id: string;
    clerkId: string;
    email: string;
    name?: string;
    avatar?: string;
    subscriptionTier: "free" | "pro" | "enterprise";
    _creationTime: number;
  };
  projects: {
    _id: string;
    userId: string;
    name: string;
    description: string;
    status: "idea" | "planning" | "development" | "testing" | "launched";
    techStack: string[];
    repositoryUrl?: string;
    _creationTime: number;
  };
  conversations: {
    _id: string;
    projectId: string;
    userId: string;
    messages: {
      role: "user" | "assistant" | "system";
      content: string;
      timestamp: number;
      metadata?: any;
    }[];
    _creationTime: number;
  };
  tasks: {
    _id: string;
    projectId: string;
    assignedTo: string;
    title: string;
    description: string;
    status: "todo" | "in_progress" | "completed" | "blocked";
    priority: "low" | "medium" | "high" | "critical";
    estimatedTime?: number;
    actualTime?: number;
    dueDate?: number;
    _creationTime: number;
  };
  codeFiles: {
    _id: string;
    projectId: string;
    path: string;
    content: string;
    language: string;
    version: number;
    _creationTime: number;
  };
  mockups: {
    _id: string;
    projectId: string;
    name: string;
    description?: string;
    imageUrl?: string;
    figmaUrl?: string;
    status: "draft" | "review" | "approved";
    _creationTime: number;
  };
  agents: {
    _id: string;
    name: string;
    type: "frontend" | "backend" | "fullstack" | "design" | "devops" | "product";
    status: "idle" | "active" | "busy" | "offline";
    capabilities: string[];
    currentTask?: string;
    model: string;
    _creationTime: number;
  };
  orchestratorSessions: {
    _id: string;
    projectId: string;
    userId: string;
    status: "active" | "paused" | "completed" | "failed";
    agents: string[];
    currentPhase: string;
    progress: number;
    _creationTime: number;
  };
}

export type ArgumentTypes<Function extends FunctionDefinition> = 
  Function extends { args: infer Args } 
    ? Args extends Record<string, any> 
      ? Args 
      : {}
    : {};

export type Builder<Function extends FunctionDefinition> = 
  Function extends { handler: infer Handler }
    ? Handler extends (...args: any) => infer Return
      ? (...args: ArgumentTypes<Function>) => Return
      : never
    : never;
